[package]
name = "sugoi"
version = "0.1.0"
authors = [ "frahz <me@frahz.dev>" ]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
low = { git = "https://git.iatze.cc/frahz/low.git" }
